package:
  name: ruby
  version: 2.0.0-p247

source:
  fn: ruby-2.0.0-p247.tar.gz
  url: http://cache.ruby-lang.org/pub/ruby/2.0/ruby-2.0.0-p247.tar.gz

requirements:
  build:
    - openssl
  run:
    - openssl
