package:
  name: wtforms
  version: 1.0.5

source:
  fn: WTForms-1.0.5.zip
  url: https://pypi.python.org/packages/source/W/WTForms/WTForms-1.0.5.zip
  md5: a7ba0af8ed65267e5b421d34940d0151
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - wtforms = wtforms:main
    #
    # Would create an entry point called wtforms that calls wtforms.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - wtforms

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://wtforms.simplecodes.com/
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
