package:
  name: hyperdex
  version: 1.1

source:
  git_tag: releases/1.1
  git_url: https://github.com/rescrv/HyperDex/

requirements:
  build:
    - python
    - libe 0.5
    - busybee
    - hyperleveldb
    - replicant
    - cython 0.18

  run:
    - python
    - libe
    - busybee
    - hyperleveldb
    - replicant

about:
  home: https://github.com/rescrv/HyperDex
  license: MIT
