package:
  name: protobuf
  version: 2.5.0

source:
  fn: protobuf-2.5.0.tar.gz
  url: https://pypi.python.org/packages/source/p/protobuf/protobuf-2.5.0.tar.gz
  md5: 338813f3629d59e9579fed9035ecd457
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - protobuf = protobuf:main
    #
    # Would create an entry point called protobuf that calls protobuf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - google.protobuf.message

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://code.google.com/p/protobuf/
  license: New BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
