package:
  name: dopy
  version: !!str 0.2.3

source:
  fn: dopy-0.2.3.tar.gz
  url: https://pypi.python.org/packages/source/d/dopy/dopy-0.2.3.tar.gz
  md5: 8d82a81d977841395077d9149ef85bb5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - dopy = dopy:main
    #
    # Would create an entry point called dopy that calls dopy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests

  run:
    - python
    - requests

test:
  # Python imports
  imports:
    - dopy

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/devo-ps/dopy
  license: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
