package:
  name: flask-csrf
  version: 0.9.2

source:
  fn: flask-csrf-0.9.2.tar.gz
  url: https://pypi.python.org/packages/source/f/flask-csrf/flask-csrf-0.9.2.tar.gz
  md5: d4474f500fcc2de4eeaea0acf659ab53
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-csrf = flask-csrf:main
    #
    # Would create an entry point called flask-csrf that calls flask-csrf.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - flask

  run:
    - python
    - distribute
    - flask

test:
  # Python imports
  imports:
    - "flaskext.csrf"

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://sjl.bitbucket.org/flask-csrf/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
