package:
  name: replicant
  version: 0.4.0

source:
  git_url: https://github.com/rescrv/Replicant
  git_tag: releases/0.4.0


requirements:
  build:
    - python
    - libe
    - busybee
    - hyperleveldb
    - po6

  run:
    - python
    - libe
    - busybee
    - hyperleveldb
    - po6

about:
  home: https://github.com/rescrv/Replicant
  license: MIT
  