package:
  name: po6
  version: 0.5.0

source:
  git_url: https://github.com/rescrv/po6
  git_tag: releases/0.5.0


requirements:
  build:
    - python

  run:
    - python

about:
  home: https://github.com/rescrv/po6
  license: MIT
  